### ISSUE TITLE
This is one of the best Music Transformers

### ISSUE THREAD

**Issue by MauriceCalvert** [spectraldoy/music-transformer#1]
Given appropriately normalised MIDI files, this transformer produces results that are truly astonishing, a head and shoulders above all the other similar projects on github.
Samples of generated Baroque music attached.
[samples.zip](https://github.com/spectraldoy/music-transformer/files/10834953/samples.zip)

**Comment by MauriceCalvert** [comment]
Closed.

**Comment by spectraldoy** [comment]
Thank you very much, I appreciate it!

Wow, those samples are much better than what I achieved! Would you mind telling me what datasets you used? Additionally, would you mind making a pull request where you add your samples to a samples folder?

**Comment by spectraldoy** [comment]
Hi @smirkingman, sorry to ping, but I'm really interested in how you were able to achieve those results. Would you be okay sharing with me the details of this model that you used, and the dataset?

**Comment by MauriceCalvert** [comment]
Hi @spectraldoy I understand your eagerness and I apologise for the delay; I discovered a subtle bug in the way the preprocessing code was handling slurs, which created glitches in the output... which means that I have to re-run. At about 4-5 hours on an A100 GPU per dataset, it's quite lengthy.

Interestingly, I had a [professional musician](https://www.google.com/search?q=albane+g%C3%A9nat) listen to the generated midis. Her opinion: The pieces vary from fair to almost-the-composer. Some structures / development / harmonies were excellent, but not truly original. Were a 3rd year bachelor student in musicology/composing be asked to write a sonata in the style of (say) Mozart, and submitted one of my samples, he would likely get a good mark.

I'll gladly let you have the samples, datasets and all the Python code to do pre-processing, learning and generating etc.; but I'm a Github noob and I have no idea how Pull Requests work.

I've been working on this for a few weeks now and I'd like to discuss how I might be able to contribute. Could we possibly take this offline before publishing?
![emailpicture](https://user-images.githubusercontent.com/22235329/222112126-d99328e8-f834-42b1-88bb-64ab85a4d7ae.jpg)

**Comment by spectraldoy** [comment]
Conversation taken offline. Closing this.
